# Below is the list of all available search engines
# Use them in search_engines as follow : "engine1,engine2,engine3..."

# anubis, baidu, bevigil, binaryedge, bing, bingapi, bufferoverun, censys, certspotter,
# crtsh, dnsdumpster, duckduckgo, fullhunt, github-code, hackertarget, hunter, intelx,
# omnisint, otx, pentesttools, projectdiscovery, qwant, rapiddns, rocketreach,
# securityTrails, sublist3r, threatcrowd, threatminer, urlscan, virustotal, yahoo,
# zoomeye

search_engines: "bing,yahoo,linkedin,urlscan,virustotal"